---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  IaC Assignment1 Create Cloud formation stack for a small business mini network

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration"
        Parameters: 
          - VPCCIDR
      - 
        Label: 
          default: "Tags"
        Parameters: 
          - ProjectName


Parameters:
  VPCId:
    Type: String

  ProjectName:
    Type: String
    Description: Enter project name
  
  InternetGatewayId:
    Type: String
    Default: InternetG 



  










     
