---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  IaC Assignment1 Create Cloud formation stack for a small business mini network

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration"
        Parameters: 
          - VPCCIDR
      - 
        Label: 
          default: "Tags"
        Parameters: 
          - ProjectName


Parameters:
  VPCId:
    Type: String

  ProjectName:
    Type: String
    Description: Enter project name


Resources:
 
  # public subnet for J instance
  PublicSubnet1:  
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Fn::ImportValue: !Ref VPCId 
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
  # private subnet for F instance    
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Fn::ImportValue: !Ref VPCId
      AvailabilityZone: !Select [ 0, !GetAZs '' ] 
      CidrBlock: 10.0.1.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
  # security group for F instance
  SecurityGroupPrivate1:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow traffic to J
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/24
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/24
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.0.0/24 
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.1.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
      VpcId: 
        Fn::ImportValue: !Ref VPCId 
  # F instance
  ec2InstanceF:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08c40ec9ead489470
      KeyName: DemoCloudForm
      SecurityGroupIds: [!Ref SecurityGroupPrivate1]
      SubnetId: !Ref PrivateSubnet1
      Tags:
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Name
          Value : Instance F           
  # private subnet for A instance
  PrivateSubnet2:  
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Fn::ImportValue: !Ref VPCId
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.0.2.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
  # A instance
  ec2InstanceA:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0753877c9c4e0fdda
      KeyName: DemoCloudForm
      SecurityGroupIds: [!Ref SecurityGroupPrivate2]
      SubnetId: !Ref PrivateSubnet2
      Tags:
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Name
          Value : instance A
# route table for instance A
  RouteTableInstA:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
      VpcId: 
        Fn::ImportValue: !Ref VPCId
  #  route for NATGat 
  NATGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0 
      NatGatewayId: !Ref NATGateway
      RouteTableId: !Ref RouteTableInstA
  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RouteTableInstA
      SubnetId: !Ref PrivateSubnet2
# NAT Gateway
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref PublicSubnet1
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      Tags:
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Name
          Value: NATGAtewayA
  NATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  # security group for A instance
  SecurityGroupPrivate2:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow traffic to A
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/24
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/24
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.0.0/24 
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.3.0/24
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.4.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
      VpcId: 
        Fn::ImportValue: !Ref VPCId        
# private subnet for D instance
  PrivateSubnet3:  
    Type: AWS::EC2::Subnet
    Properties: 
      VpcId: 
        Fn::ImportValue: !Ref VPCId
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.0.3.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
# private subnet for D instance 
  PrivateSubnet4:  
    Type: AWS::EC2::Subnet
    Properties: 
      VpcId: 
        Fn::ImportValue: !Ref VPCId
      AvailabilityZone: !Select [ 3, !GetAZs '' ]
      CidrBlock: 10.0.4.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
# D instance (database)
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref DBSubnet
      DBInstanceIdentifier: DemoDB
      VPCSecurityGroups:
        - !GetAtt DBEC2SecurityGroup.GroupId
      AllocatedStorage: "5"
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: sa
      MasterUserPassword: "12345678"
      Tags:
        - Key: Name
          Value: D
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
  # Database subnet group
  DBSubnet:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: DemoDBSubnetGroup
      DBSubnetGroupDescription: DemoDBSubnetGroup
      SubnetIds:
        - !Ref PrivateSubnet3
        - !Ref PrivateSubnet4
      Tags:
        - Key: Name
          Value: DemoDBSubnetGroup
  # D instance security group
  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: 
        Fn::ImportValue: !Ref VPCId
      GroupName: DemoDBSesurityGroup
      GroupDescription: Allow postgres inbound traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: DemoDBSesurityGroup
 # internet Gateway
  InternetG:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
  # Gateway attachment
  MyVPCGatewayattachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetG
      VpcId: 
        Fn::ImportValue: !Ref VPCId
  # route table 
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
      VpcId: 
        Fn::ImportValue: !Ref VPCId
  # public route 
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: MyVPCGatewayattachment
    Properties:
      DestinationCidrBlock: 0.0.0.0/0 
      GatewayId: !Ref InternetG
      RouteTableId: !Ref RouteTable
  # public subnet
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref PublicSubnet1
  # security group for public
  SecurityGroupPublic:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
# allowing traffic to F
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.1.0/24
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.1.0/24
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.1.0/24
 # allowing traffic to A         
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.2.0/24
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.2.0/24
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.2.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
      VpcId: 
        Fn::ImportValue: !Ref VPCId 
# J instance
  ec2InstanceJ:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08c40ec9ead489470
      KeyName: DemoCloudForm
      SecurityGroupIds: [!Ref SecurityGroupPublic]
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Name
          Value : Instance J    











     
