---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  IaC Assignment1 Create Cloud formation stack for a small business mini network

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Network Configuration"
        Parameters: 
          - VPCCIDR
      - 
        Label: 
          default: "Tags"
        Parameters: 
          - ProjectName
          - ProjectID
          - ResourceName   

Parameters:
  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
    AllowedValues:
      - 10.0.0.0/16
      - 10.0.0.0/24
    Description: Enter VPC CIDR

  ProjectName:
    Type: String
    Description: Enter project name
  
  ProjectID:
    Type: String
    Description: Enter project ID

  ResourceName:
    Type: String
    Description: Enter Resource name

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : !Ref ResourceName  
  
  PublicSubnet1:  
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-1
      CidrBlock: 10.0.0.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : PublicSubnet1
      VpcId: !Ref MyVPC

  PrivateSubnet1:  
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-1
      CidrBlock: 10.0.1.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : PrivateSubnet1
      VpcId: !Ref MyVPC    

  PrivateSubnet2:  
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-2
      CidrBlock: 10.0.2.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : PrivateSubnet2
      VpcId: !Ref MyVPC    

  PrivateSubnet3:  
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-2
      CidrBlock: 10.0.3.0/24
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : PrivateSubnet3
      VpcId: !Ref MyVPC    

  InternetG:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : InternetGateway

  MyVPCGatewayattachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetG
      VpcId: !Ref MyVPC
      VpnGatewayId: String

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : RouteTable
      VpcId: !Ref MyVPC





     
