#VPC
Parameters:
  VPCId:
    Type: String
    Default: MyVPC  
  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
    AllowedValues:
      - 10.0.0.0/16
      - 10.0.0.0/24
    Description: Enter VPC CIDR
  ProjectName:
    Type: String
  ProjectID:
    Type: String
  ResourceName:
    Type: String  
    
Resources:  
  MyVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
       
Outputs:
  MyVPC:
    Value:
      Ref: MyVPC
    Export:
      Name: !Ref VPCId