#VPC
Parameters:
  VPCId:
    Type: String
    Default: MyVPC  
  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
    AllowedValues:
      - 10.0.0.0/16
      - 10.0.0.0/24
    Description: Enter VPC CIDR
  ProjectName:
    Type: String
  InternetGatewayId:
    Type: String
    Default: InternetG 
Resources:  
  MyVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
 # internet Gateway
  InternetG:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key : Project Name
          Value : !Ref ProjectName
  # Gateway attachment
  MyVPCGatewayattachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetG
      VpcId: !Ref MyVPC


Outputs:
  MyVPC:
    Value:
      Ref: MyVPC
    Export:
      Name: !Ref VPCId
  InternetG:
    Value: 
      Ref: InternetG
    Export:
      Name: !Ref InternetGatewayId

  